### ISSUE TITLE
Adding default (no arg) constructor for TokenHolderDeserializer for AWS SAM Implementation

### ISSUE THREAD

**Issue by mgrahadhuita** [auth0/auth0-java#445] opened 2022-07-27 08:16 UTC
### Describe the problem you'd like to have solved

I've been getting this issue when i was trying to use token request in AWS SAM / lambda using java : 
```


2022-07-27 08:01:09,983 ERROR [com.gro.par.ser.TokenServiceImpl] (Lambda Thread (NORMAL)) [generateToken] api exception - error : : com.auth0.exception.APIException: Request failed with status code 200: Failed to parse the response body.
--
at com.auth0.net.ExtendedBaseRequest.parseResponse(ExtendedBaseRequest.java:72)
at com.auth0.net.BaseRequest.execute(BaseRequest.java:35)
at com.gro.pari.service.TokenServiceImpl.generateToken(TokenServiceImpl.java:55)
at com.gro.pari.TokenHandler.handleRequest(TokenHandler.java:48)
at com.gro.pari.TokenHandler.handleRequest(TokenHandler.java:18)
at io.quarkus.amazon.lambda.runtime.AmazonLambdaRecorder$1.processRequest(AmazonLambdaRecorder.java:170)
at io.quarkus.amazon.lambda.runtime.AbstractLambdaPollLoop$1.run(AbstractLambdaPollLoop.java:130)
at java.lang.Thread.run(Thread.java:829)
at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:597)
at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:194)
Caused by: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Class com.auth0.json.auth.TokenHolderDeserializer has no default (no arg) constructor
at [Source: (String)"
at com.fasterxml.jackson.databind.DeserializationContext.reportBadDefinition(DeserializationContext.java:1904)
```

seems like no arg constructor was needed if i want to use it on AWS SAM, since it was okay if i try to use it for local project.

### Describe the ideal solution

To add default (no arg) constructor for TokenHolderDeserializer class.

**Comment by poovamraj** [comment] 2022-07-27 21:02
@mgrahadhuita Please ensure no sensitive information is shared through the stacktrace.

Also, the class mentioned  - `TokenHolderDeserializer` already has a default constructor.  Can you share the sample code that causes the issue.

**Comment by poovamraj** [comment] 2022-07-31 14:30
@mgrahadhuita also can you share the version of the library you are using, along with the Java version used to run the code?

**Comment by poovamraj** [comment] 2022-08-07 21:25
Hi @mgrahadhuita we couldn't reproduce this issue on our end for now. We will close this issue for now but feel free to reopen this with more details.

**Closed by poovamraj** 2022-08-07 21:25 UTC
Labels: waiting for customer
