### ISSUE TITLE
Auto-refresh of API Token for Management APIs

### ISSUE THREAD

**Issue by krisnik** [auth0/auth0-java#473] opened 2022-11-16 09:50 UTC
### Describe the problem you'd like to have solved

Continuing from [Auth0 Java SDK - Refreshing Management API Token](https://community.auth0.com/t/auth0-java-sdk-refreshing-management-api-token/93857)

### Describe the ideal solution

The SDK should internally handle the management api token and refresh it when required. 
## Alternatives and current work-arounds

1. Handle the API exception, refresh token and re-run the request.
2. Store tokenExpiresAt and refresh the token when managementAPI instance is required. Something in the lines of
```java
public ManagementAPI getManagementAPI() {

    if (currentTime > tokenExpiresAt) {
        refreshToken();
        managementApi.setApiToken("new token");
    }

    return managementApi;
}
```
3. Have a background thread that refreshes the token at defined periodicity.

All the three workarounds have their own set of challenges. So, it would be ideal if SDK handles the token renewal.

**Comment by jimmyjames** [comment] 2022-11-30 01:33
Thanks for raising @krisnik! We are looking into if this is something we can add to v2, will follow-up when we know more.

I'm curious if you could expand on the challenges of option 2) you listed above? Wondering if there's additional challenges beyond the increased verbosity of needing to always call `getManagementAPI()` before every API call.

**Comment by krisnik** [comment] 2022-11-30 05:09
@jimmyjames - Any tentative timelines you have for v2 availability? 

I cannot enforce "getManagementAPI()" in the code via some rules. So, if someone caches the object - `ManagementAPI mgmtAPI` in their class and initializes it only once, the client will get expired in the next 24 hours, unless some other thread updates the token via another `getManagementAPI()` call. 

These will be hard to test / identify as the token may / may not get refreshed.

**Comment by jimmyjames** [comment] 2022-12-07 01:26
Thanks @krisnik! 

v2 is scheduled for a beta in early 2023, with a GA release to follow shortly.

If you have thoughts or would like to try out our solution in #479, please chime in there - thanks! 🚀

**Comment by jimmyjames** [comment] 2023-01-31 03:55
Closing this for now, as we've added a stub `TokenProvider` in v2 beta that we can provide sync and async implementations for in the future.

**Closed by jimmyjames** 2023-01-31 03:55 UTC
Labels: feature request

**Comment by kronaemmanuel** [comment] 2023-03-17 14:20
@jimmyjames any update on the `TokenProvider` for v2?

**Comment by Andro999b** [comment] 2023-05-11 11:12
Does lib support autorefresh?

**Comment by MatMoore** [comment] 2023-05-16 15:09
Hi @jimmyjames 

I see that the TokenProvider interface was added in v2, however am I right in thinking that the auto refreshing implementation is not added yet? The [Builder](https://github.com/auth0/auth0-java/blob/2.3.0/src/main/java/com/auth0/client/mgmt/ManagementAPI.java#L370) class hard codes this to `SimpleTokenProvider` and there is no way to override it.

Is this something that is currently being worked on, or could you point me to an up to date workaround?

**Comment by oliverhenlich** [comment] 2025-02-27 22:02
> I see that the TokenProvider interface was added in v2, however am I right in thinking that the auto refreshing implementation is not added yet? The [Builder](https://github.com/auth0/auth0-java/blob/2.3.0/src/main/java/com/auth0/client/mgmt/ManagementAPI.java#L370) class hard codes this to `SimpleTokenProvider` and there is no way to override it.
> 
> Is this something that is currently being worked on, or could you point me to an up to date workaround?

It is still unclear to me what the status of this is or why it was closed.
Is the intention for us to implement a refreshing TokenProvider (which I'm happy to do)?
The problem is that the ManagementAPI.Builder does not provide a way to supply a TokenProvider.
And the only place the ManagementAPI instance can be created with a TokenProvider is via the private constructor.
```
private ManagementAPI(String domain, TokenProvider tokenProvider, Auth0HttpClient httpClient) {
```

Should we be using a horrible reflection hack to call this constructor in the meantime? What is the plan?

**Comment by muliyul** [comment] 2025-07-17 10:36
We're also suffering from this and we manage boilerplate for something which should be handled by the SDK.
