### ISSUE TITLE
Please Support Custom Domains (Auth0 feature) 

### ISSUE THREAD

**Issue by DimitriLubenski** [auth0/auth0-java#104] opened 2018-01-29 20:54 UTC
Provided the tenant is configured using the custom domain login.mycompany.com.

Provided the controller initialized this way, where domain parameter is defined as login.mycompany.com

controller = AuthenticationController
                    .newBuilder(domain, clientId, clientSecret)
                     .build();

Generally, if I use a custom domain login.mycompany.com the authentication url should be login.mycompany.com/authorize?… while the java client should communicate with mycompany.auth0.com/userinfo in the background (as described in the list of limitations of custom domain feature). To assure this we have "withAudience" method, which is in this example set to mycompany.auth0.com

        AuthorizeUrl urlBuilder = controller
                .buildAuthorizeUrl(req, redirectUri)
                .withScope("openid profile email")
                .withAudience(String.format("https://%s/userinfo", appConfig.getAudience()));

The generated AutorizeURL is perfectly right, but the background communication is performed to login.mycompany.com, which causes 401. There should be an option to configure either the custom domain or respect the audience parameter. 

The workaround is here (but for sure it is not very straight forward)
       //Pass audience as a parameter instead of domain
AuthenticationController
                    .newBuilder(audience, clientId, clientSecret)

        //The library does not support the custom domains yet. We have to replace the audience domain with the custom domain in the authorize URL
        String audienceURL = String.format("https://%s/authorize", StringUtils.trim(appConfig.getAudience()));
        String customDomainURL = String.format("https://%s/authorize", StringUtils.trim(appConfig.getDomain()));
        
        redirectURL = StringUtils.replace(redirectURL, audienceURL, customDomainURL);

**Comment by lbalmaceda** [comment] 2018-01-30 17:21
Hi @DimitriLubenski. Custom Domains are supported out of the box on existing SDKs just by using the custom domain instead of the auth0 tenant one. This means that if your auth0 tenant is `mycompany.auth0.com` you would use `login.mycompany.com` when initializing the `AuthAPI` instance.
For built-in APIs such as "userinfo" and "management v2" you still need to use the auth0 tenant domain as pointed out in our [custom domain docs](https://auth0.com/docs/custom-domains#apis). So if you require this particular audience you would call `withAudience("https://mycompany.auth0.com/userinfo")` or you would get an invalid service/api error.

Authentication using response type code (default and recommended) is a 2 step process. Full working example:

```java
AuthAPI authAPI = new AuthAPI("login.mycompany.com", "REPLACE_WITH_CLIENT_ID", "REPLACE_WITH_CLIENT_SECRET");
authAPI.setLoggingEnabled(true); //just for debugging

String authUrl = authAPI.authorizeUrl("https://jwt.io") //or any allowed callback url
   .withAudience("https://mycompany.auth0.com/userinfo")
   build();

//Redirect the user to the "authUrl" and wait for them to log in

```

when you receive the call on the callback url with the code, finish the authentication

```java
//exchange the received code to finish the flow

TokenHolder tokens = authAPI.exchangeCode("RECEIVED_CODE", "https://jwt.io")
   .setAudience("https://mycompany.auth0.com/userinfo")
   .execute();
```


This SDK relies on the Authentication and Management [Auth0 APIs](https://auth0.com/docs/api/info). The `AuthorizeUrlBuilder` provided in the `AuthAPI` class is only meant to generate valid URLs pointing to the /authorize endpoint, which displays the Universal Login Page hosted by Auth0. The background communication you mention will always respect the domain set when the client was instantiated, so it's up to you to properly configure the Custom Domain on your tenant's settings in the [dashboard](https://manage.auth0.com/#/tenant/custom_domains). If you've skipped this step please follow the [guide](https://auth0.com/docs/custom-domains).

Cheers.

**Comment by DimitriLubenski** [comment] 2018-02-12 18:11
Hi Luciano,

I know, what my issue is. I am following the guide for spring integration, which relies on the follwing bean configuration: 

@Bean
public AuthenticationController authenticationController() throws UnsupportedEncodingException {
    return AuthenticationController.newBuilder(domain, clientId, clientSecret)
            .build();
}

If I set the domain to the custom domain, it uses it in the communication for the "audience", which leads to exceptions. 

controller.buildAuthorizeUrl(...)

uses this domain for the /autorize URL, which is right. I suppose, the AuthenticationController  should have the audience parameter as well as the domain parameter to cover the custom domain use case.

**Comment by lbalmaceda** [comment] 2018-02-12 18:38
Can you please post the link to the guide you're following? thanks

**Comment by DimitriLubenski** [comment] 2018-02-12 18:39
https://auth0.com/docs/quickstart/webapp/java-spring-security-mvc/01-login

**Comment by lbalmaceda** [comment] 2018-02-12 18:54
The sample relies on the [mvc-common](https://github.com/auth0/auth0-java-mvc-common) library. The AuthenticationController will work just fine if you pass your custom domain as the domain parameter. But note as I said in my first comment:

> For built-in APIs such as "userinfo" and "management v2" you still need to use the auth0 tenant domain as pointed out in our [custom domain docs](https://auth0.com/docs/custom-domains#apis). 

This means that, at least in the sample you've linked, you'd need to edit the method that it's generating the Authorize URL and make it use as audience your Auth0 domain instead of the custom domain. (Because the sample is using /userinfo audience). You can extract this "auth0 domain" to another property in the `resources/auth0.properties` file and read it on the `AppConfig` class.

Change this:
![image](https://user-images.githubusercontent.com/3900123/36113745-9bb18518-100c-11e8-9133-0cb9a622c561.png)

To this:
![image](https://user-images.githubusercontent.com/3900123/36113738-9566ca10-100c-11e8-9743-2ff5f2c43e6c.png)

**Comment by DimitriLubenski** [comment] 2018-02-12 19:04
That was also my first thought. Unfortunately it does not work (Request failed with status code 401: Unauthorized). The only way to get it working is to initialize the AuthenticationController with original domain AND assure the authorizeURL is "hacked" to point to the custom-domain (for sure the audience will contain the original auth0 domain).

**Comment by lbalmaceda** [comment] 2018-02-12 19:20
I've made the changes shown in my previous comment and the sample works fine (I can log in in https://localhost:8080). 

In the `/resources/auth0.properties` file I'm using the details of my auth0 client. In particular for the domain I'm using the **custom domain** associated with my tenant. The only change left is in the `LoginController` where I request the userinfo audience using my **auth0 domain** instead of the one previously set up in the properties file:

Just to be verbose. It should look like this:

`AppConfig`:
```java
@Bean
public AuthenticationController authenticationController() throws UnsupportedEncodingException {
    return AuthenticationController.newBuilder("https://login.mycompany.com", {MY_CLIENT_ID}, {MY_CLIENT_SECRET)
            .build();
}
```


`LoginController`:
```java
String authorizeUrl = controller.buildAuthorizeUrl(req, redirectUri)
        .withAudience("https://mycompany.auth0.com/userinfo")
        .build();
```

If you can't log in probably there's a configuration issue in your tenant or client. I recomment you to check the quickstart steps again and don't hesitate to contact [support](https://support.auth0.com) if you need further guidance.

**Comment by DimitriLubenski** [comment] 2018-02-12 19:34
That is exactly what I do. In the log I see (if debugging is enabled), that the token exchange goes to https://login.mycompany.com which causes "Unauthorized" (that is expected because it may not go to the custom domain according to the documentation). The reason is, that even if the .withAudience set to https://mycompany.auth0.com/userinfo, this is only applied to the authorizationURL itself and not to the token exchange flow happening later. So the only way I can get it working is this one

return AuthenticationController.newBuilder("https://mycompany.auth0.com/userinfo", {MY_CLIENT_ID}, {MY_CLIENT_SECRET).build();
....
String authorizeUrl = controller.buildAuthorizeUrl(req, redirectUri)
        .withAudience("https://mycompany.auth0.com/userinfo")
        .build();
...
//Replace the original with the custom domain in the URL.
if (!StringUtils.isEmpty(appConfig.getCustomDomain())){
            try {
                URL url = new URL(redirectUrl);
                redirectUrl = String.format("%s://%s%s", url.getProtocol(), url.getAuthority(), url.getFile());
            }
            catch (MalformedURLException e) {
                throw new RuntimeException(e);
            }
        }

Cheers

**Comment by darkyen** [comment] 2018-02-16 03:38
Hi Dimitri, 

We tried reproducing the issue however we were not able to replicate the issue with the latest versions of the SDKs, as this seems like a use-case specific case, we'd like to move the conversation to support-center and handle it appropriately. I have opened a ticket for you and we'll reach out to you via support center.

**Comment by lbalmaceda** [comment] 2018-02-16 14:00
I'll proceed and close this issue then.

**Closed by lbalmaceda** 2018-02-16 14:00 UTC
