### ISSUE TITLE
OkHttpClient response not closed on exception

### ISSUE THREAD

**Issue by pnam0228** [auth0/auth0-java#447] opened 2022-08-05 18:30 UTC
### Describe the problem you'd like to have solved
`okhttp3.OkHttpClient - A connection to {some_auth0_url} was leaked. Did you forget to close a response body?`
We're seeing this warning sometimes when calling `TokenRequest.execute()` at times. I believe `response` here 
```
 @Override
            public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
                try {
                    T parsedResponse = parseResponse(response);
                    future.complete(parsedResponse);
                } catch (Auth0Exception e) {
                    future.completeExceptionally(e);
                }
            }
```
should be closed in the `catch` block.

### Describe the ideal solution
Replace 
```
catch (Auth0Exception e) {
                    future.completeExceptionally(e);
                }
```
with 
```
catch (Auth0Exception e) {
                    response.close();
                    future.completeExceptionally(e);
                }
```
## Alternatives and current work-arounds
The warning doesn't much affect our application, so we're ignoring it.

**Comment by poovamraj** [comment] 2022-08-07 21:26
Hi @pnam0228, thank you for raising this issue with clear details. We will take a look into it and fix this issue.

**Comment by jimmyjames** [comment] 2022-08-24 19:09
Thanks @pnam0228. Can you provide some sample code and/or failures conditions to reproduce? I'm not able to reproduce, and am seeing the response closed on exception cases (both for synchronous and asynchronous request executions).

Also curious, you mention observing the issue at times with `TokenRequest.execute()`, but the code sample and suggested change is in the async execution (`executeAsync`). Have you observed issues with `execute()`, `executeAsync()`, or both?

FWIW, OkHttp will close the response when it is executed within a try block, or when several other methods on the response body are called, as documented [here](https://square.github.io/okhttp/4.x/okhttp/okhttp3/-response-body/). If we can get a scenario in which we can reproduce this issue we can further investigate to figure out the scenario causing the response to not close. Thanks!

**Comment by jimmyjames** [comment] 2022-10-05 02:06
Closing this since we can't reproduce. Please chime in or open a new issue with reproducible steps if the issue persists so we can look into it.

**Closed by jimmyjames** 2022-10-05 02:06 UTC
Labels: waiting for customer
