### ISSUE TITLE
Add "jobs" API calls to java client library

### ISSUE THREAD

**Issue by crizo23** [auth0/auth0-java#114] opened 2018-03-19 23:12 UTC
Or am I missing this in the java library? I need to make calls such as: https://auth0.com/docs/api/management/v2#!/Jobs/post_verification_email

**Comment by lbalmaceda** [comment] 2018-03-20 13:54
I'm closing this as it's a dupe of https://github.com/auth0/auth0-java/issues/62.

**Closed by lbalmaceda** 2018-03-20 13:54 UTC
